services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    ports:
      - 3306:3306
    network_mode: bridge
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_storage:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    network_mode: bridge
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

volumes:
  ollama_storage: